packages:
  - apps/*
  - packages/*
autoInstallPeers: false
packageExtensions:
  '@dcloudio/uni-mp-vite@3.0.0-5020420260813003':
    dependencies:
      estree-walker: 2.0.2
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  core-js: false
  core-js-pure: false
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@angular-devkit/core@22.2.0'
  - '@angular-devkit/schematics-cli@22.2.0'
  - '@angular-devkit/schematics@22.2.0'
  - '@nestjs/cli@12.0.6'
  - eslint-plugin-vue@10.11.1
