import type { components } from '../../../../../packages/api-client/src/generated'
export type Member = components['schemas']['MemberDto']
export type Session = components['schemas']['SessionDto']
export type Activity = components['schemas']['ActivityDto']
export type Registration = components['schemas']['RegistrationDto']
export type MyRegistration = components['schemas']['MyRegistrationDto']
export type RegistrationInput = components['schemas']['RegistrationInput']
export type PublicMember = components['schemas']['PublicMemberDto']
export type ActivityWriteInput = components['schemas']['ActivityWriteInput']
export type ManagedActivity = components['schemas']['ManagedActivityDto']
export type OrganizerRegistration = components['schemas']['OrganizerRegistrationDto']
export type ActivityNotification = components['schemas']['NotificationDto']
export type ReadingList = components['schemas']['ReadingListDto']
export type ReadingStats = components['schemas']['ReadingStatsDto']

export type ProfileDetails = components['schemas']['ProfileDetailsDto']
export type ProfileDetailsInput = components['schemas']['ProfileDetailsInput']
export type CardSettings = components['schemas']['CardSettingsDto']
export type MemberCard = components['schemas']['MemberCardDto']
export type Attendance = components['schemas']['AttendanceDto']
export type Comment = components['schemas']['CommentDto']
export type Review = components['schemas']['ReviewDto']
export type CommentList = components['schemas']['CommentListDto']
export type ReviewList = components['schemas']['ReviewListDto']
export type FeedbackContext = components['schemas']['FeedbackContextDto']
export type ReviewStats = components['schemas']['ReviewStatsDto']
export type AiActivityDraft = components['schemas']['ActivityDraftDto']
export type AiActivityDraftResult = components['schemas']['ActivityDraftResultDto']
